### ISSUE TITLE
[feature request] mysql resource provisioner

### ISSUE THREAD

**Issue by astromechza** [score-spec/score-compose#128]
Mysql is one of the most commonly used databases! Let's support that!

This should be a relative clone of the postgres provisioner, but specific to mysql. For packing reasons, we should also use a single mysql _instance_ which hosts a _database_ per resource.

See https://hub.docker.com/_/mysql for the docker image and various environment variables that can be used.

**Comment by giesan** [comment]
Hello everyone,
I would like to take over this issue, but I have no rights to assign these issues to myself. 
Can someone with the appropriate rights please do this?
Many thanks and best regards
Andrej

**Comment by sujaya-sys** [comment]
@giesan done! Thanks for looking into this one 🙂

**Comment by giesan** [comment]
@sujaya-sys Thank you.

**Comment by astromechza** [comment]
Closed in #132
