### ISSUE TITLE
[feature request] Support generic OCI image in `init --provisioners`

### ISSUE THREAD

**Issue by mathieu-benoit** [score-spec/score-compose#178]
To complete https://github.com/score-spec/score-compose/pull/175, it would be great to support generic OCI image to import external provisioners.

https://opencontainers.org/

Example:
```
score-compose init --provisioners oci://...
```

Wondering if for this we could use the ORAS client:
- https://oras.land/
- https://github.com/oras-project/oras-go/blob/main/example_test.go

**Comment by astromechza** [comment]
@mathieu-benoit how would that work? What would the archive format be inside the image and how would users create an image file with a single yaml file inside it?

**Comment by mathieu-benoit** [comment]
Simple as:
```
oras push registry/name:tag my-provisioner.yaml
```

Then you can use it:
```
oras pull registry/name:tag
```

Or more embedded:
```
score-compose init --provisioners registry/name:tag
```

Why it's appealing? Because you now have your provisioners as OCI artifacts in your private secure artifact/container registry.

**Comment by astromechza** [comment]
Ah ok I see so this is a common pattern used in `oras` 👍 .

So `score-k8s init --provisioners oci://reg/name:tag` would be fairly equivalent to 

```
score-k8s init
oras pull oci://reg/name:tag --output .score-k8s
```

Thankfully looks like there's a useful go library here: https://github.com/oras-project/oras-go.

Cool @mathieu-benoit I think this is a good idea. Note that we MUST keep the oci:// or oras:// scheme prefix on the URI to unambiguate it.

**Comment by astromechza** [comment]
Also note: This would import ALL the files from that oci reference: all provisioner files and possibility utility scripts as needed.

**Comment by mathieu-benoit** [comment]
Yup, I think `oci://` is the right approach, very generic, and that's what `oras` recommends too.

And yes, you can do this below to upload multiple files let's say in a folder:
```
oras push registry/name:tag my-folder-container-files/
```

**Comment by 7h3-3mp7y-m4n** [comment]
hey, since it's a good first issue, Can I try to fix it?

**Comment by sujaya-sys** [comment]
@7h3-3mp7y-m4n For sure, that sounds great! You can go ahead and assign the issue to yourself whenever you're ready to get started. If you have any questions in regards to the implementation @mathieu-benoit and @delca85 should be able to assist. Thanks a lot!

**Comment by 7h3-3mp7y-m4n** [comment]
thanks @mathieu-benoit  and @sujaya-sys  I'll start working on this and I'll be happy if you folks could help me if I run into some confusion :)

**Comment by mathieu-benoit** [comment]
@7h3-3mp7y-m4n , like discussed offline, the implementation of this needs to actually happen in the https://github.com/score-spec/score-go repo, see example here: https://github.com/score-spec/score-go/pull/45.
And then, we will be able to release a new version of `score-go` and include it here for this OCI support (and in `score-k8s` in the meantime ;)).

**Comment by 7h3-3mp7y-m4n** [comment]
Thanks @mathieu-benoit  :)

**Comment by mathieu-benoit** [comment]
Good progress here, it's now in `score-go` 1.8.3: https://github.com/score-spec/score-go/releases/tag/v1.8.3.

We'll need to do the following things next in order to officially released this new feature:
- [X] Integrate `score-go` 1.8.3 in `score-compose`: https://github.com/score-spec/score-compose/pull/194
- [X] Integrate `score-go` 1.8.3 in `score-k8s`: https://github.com/score-spec/score-k8s/pull/63
- [ ] Test/validate this new feature integrated in `score-compose`'s `main`
- [ ] Test/validate this new feature integrated in `score-compose`'s `main`
- [ ] In https://github.com/score-spec/score-k8s/blob/main/main_init.go#L170 add the oci:// example
- [ ] In https://github.com/score-spec/score-compose/blob/main/internal/command/init.go#L228 add the oci:// example
- [ ] In https://github.com/score-spec/docs/blob/main/content/en/docs/score%20implementation/score-compose/cli.md?plain=1#L52 add the oci:// example
- [ ] In https://github.com/score-spec/docs/blob/main/content/en/docs/score%20implementation/score-k8s/cli.md?plain=1, add the provisioner parameter missing here, like we have in score-compose doc just above.

**Comment by mathieu-benoit** [comment]
Now implemented in https://github.com/score-spec/score-compose/releases/tag/0.20.0 and https://github.com/score-spec/score-k8s/releases/tag/0.1.15, with the integration of https://github.com/score-spec/score-go/releases/tag/v1.8.4. Closing now!
