### ISSUE TITLE
[Bug] Duplicate error message shown

### ISSUE THREAD

**Issue by sujaya-sys** [score-spec/score-compose#30]
### How to reproduce

This issue can be reproduced by triggering any error message. For example:

run `score-compose run -f ./score.yaml -o ./compose.yaml`  with the following `score.yaml` file:

```
apiVersion: score.dev/v1b1

metadata:
  name: sample-service

containers:
  hello:
    image: busybox
    command: "/bin/sh"
```

An error is thrown as `command` should be set to `["/bin/sh"]`

### Actual behaviour

The error output on score-compose is a little messy. It starts with the error message, then the help text and then the error message again.

```
Error: validating workload spec: 1 error(s) decoding:

* 'containers[hello].command': source data must be an array or slice, got string
Usage:
  score-compose run [flags]

Flags:
      --build string       Replaces 'image' name with compose 'build' instruction
      --env-file string    Location to store sample .env file
  -f, --file string        Source SCORE file (default "./score.yaml")
  -h, --help               help for run
  -o, --output string      Output file
      --overrides string   Overrides SCORE file (default "./overrides.score.yaml")
      --verbose            Enable diagnostic messages (written to STDERR)

validating workload spec: 1 error(s) decoding:

* 'containers[hello].command': source data must be an array or slice, got string
```
### Expected Behaviour

* Remove the "help" message on application errors, and only show it if there is a usage error.
* Remove the second error message

```
Error: validating workload spec: 1 error(s) decoding:

* 'containers[hello].command': source data must be an array or slice, got string
```

### Scope
All application errors in score-compose and score-helm

**Comment by astromechza** [comment]
👍 I'll be fixing this today.
